# Generated by Django 5.0.3 on 2024-03-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productmaterial_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='material',
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='material',
            field=models.ManyToManyField(to='product.material'),
        ),
    ]
