# Generated by Django 5.0.3 on 2024-03-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productmaterial_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='material',
            field=models.ManyToManyField(related_name='materials', to='product.material'),
        ),
    ]
